# Site settings
title: Daniel Cabral de Souza
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/daniel.jpeg'
bkimage: '/images/background.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Daniel Cabral de Souza'
  email: daniel-cabral14@hotmail.com
  twitter_username: danielcsouza97
#  facebook_username: joshgerdes
  github_username:  DanielCabral
  linkedin_username:  daniel-cabral-3a5032148
#meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
font-awesome:
  assets: true